### ISSUE TITLE
timed out after about 4000 products

### ISSUE THREAD

**Issue by fourg6x** [lagenar/shopify-scraper#1]
`Traceback (most recent call last):
  File "shopify.py", line 132, in <module>
    extract_products(fix_url(sys.argv[1]), 'products.csv')
  File "shopify.py", line 116, in extract_products
    for product in extract_products_collection(url, handle):
  File "shopify.py", line 103, in extract_products_collection
    products = get_page(url, page, col)
  File "shopify.py", line 21, in get_page
    data = urllib.request.urlopen(req).read()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 430:`

Any suggestions?

**Comment by lagenar** [comment]
Hi fourg6x, can you send me the site you were trying to scrape?

**Comment by fourg6x** [comment]
Ah, I would prefer not to say!  👶
